export const BADGE_COLOR = '#2563eb';
export const BADGE_MAX_COUNT = 999;
export const SEARCH_DEBOUNCE_MS = 150;
export const MAX_VALUE_PREVIEW_LENGTH = 80;
export const MAX_NAME_DISPLAY_LENGTH = 30;
export const NETSCAPE_HEADER =
  '# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by CookiePeek.\n\n';
export const MAX_CHANGE_LOG = 50;
export const LIVE_UPDATE_DEBOUNCE_MS = 300;
export const BADGE_FLASH_COLOR = '#f59e0b';
export const BADGE_FLASH_MS = 600;
